### ISSUE TITLE
Question, how does one set an admin password?

### ISSUE THREAD

**Issue by kz-n** [MisterCalvin/pterodactyl-swat4-egg#3]
Sorry for asking here, but i dont know where else to find this information, Trying to set up a SWAT 4 server to play with my friends but i dont know where to set my admin password

**Comment by MisterCalvin** [comment]
Are you using this egg? If so, you can set the `ADMIN_PASSWORD` variable in the panel. If you're not using this egg, you can set it in `Content/System/SwatGUIState.ini` (or `ContentExpansion`, for TSS), you'll find a variable labeled `AdminPassword` under `[SwatGame.SwatGUIConfig]`. If you don't see it you can just add in.
