### ISSUE TITLE
Failed to run pre-boot process: environment/docker: failed to create container: Error response from daemon: No such image: ghcr.io/parkervcp/yolks:wine_latest

### ISSUE THREAD

**Issue by maudelv** [MisterCalvin/pterodactyl-swat4-egg#4]
Hi, when running the Pterodactyl Server i get this error:

```[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/yolks 
 
[Pterodactyl Daemon]: Finished pulling Docker container image
container@pterodactyl~ Error Event [30573258-138e-4201-9330-544db834e6eb]: environment/docker: failed to run pre-boot process: environment/docker: failed to create container: Error response from daemon: No such image: ghcr.io/parkervcp/yolks:wine_latest
container@pterodactyl~ Server marked as offline...
```

Pterodactyl installation is running on ARM.

**Comment by MisterCalvin** [comment]
Parker does not build wine images for `arm64` (you can see [wine_latest](https://github.com/users/parkervcp/packages/container/yolks/299607692?tag=wine_latest) is only tagged for amd64), and by looking at the workflow, I can [confirm this](https://github.com/pelican-eggs/yolks/blob/master/.github/workflows/wine.yml#L36). I don't have any time at the moment to build a wine yolk with arm64 support, so I recommend you use my alternative project below, which has support for running a standalone SWAT 4 dedicated server on arm64 (without Pterodactyl support)

[MisterCalvin/swat4-server-docker](https://github.com/MisterCalvin/swat4-server-docker)

Edited to remove incorrect advice
